insert
	$eco1 isa platform, has name "ECO-1";
	$ds1 isa dataset, has name "UDC";
	$ds2 isa dataset, has name "STAPP";
	$aws1 isa environment, has name "AWS PROD US-EAST-1B";
	$aws2 isa environment, has name "AWS PROD <Main>";
	$aws3 isa environment, has name "AWS PROD <LG>";
	$aws4 isa environment, has name "AWS DP <ProdInternal>";
	$cis isa organization, has name "CIS";
	$py isa person, has name "Phil Young";
	$haproxy isa tool, has name "HAProxy";
	$whirlpool isa tool, has name "Whirlpool";
	$kafka isa tool, has name "Kafka 1";
	$kafka2 isa tool, has name "Kafka 2";
	$kafka-mirror isa tool, has name "Kafka-Mirror";
	$nifi isa tool, has name "NiFi";
	$pheonix isa tool, has name "Pheonix";
	$hive isa tool, has name "Hive";

	(tool-has-environment: $haproxy, tool-has-environment: $whirlpool, tool-has-environment: $kafka, environment-has-tool: $aws1) isa environment-tool;
	(tool-has-environment: $kafka-mirror, environment-has-tool: $aws2) isa environment-tool;
	(tool-has-environment: $kafka2, environment-has-tool: $aws3) isa environment-tool;
	(tool-has-environment: $nifi, tool-has-environment: $pheonix, tool-has-environment: $hive, environment-has-tool: $aws4) isa environment-tool;
	(source: $haproxy, destination: $whirlpool) isa process;
	(source: $whirlpool, destination: $kafka) isa process;
	(source: $kafka, destination: $kafka-mirror) isa process;
	(source: $kafka-mirror, destination: $kafka2) isa process;
	(source: $kafka, destination: $nifi) isa process;
	(source: $nifi, destination: $pheonix) isa process;
	(source: $pheonix, destination: $hive) isa process;
	(source: $hive, destination: $ds1, destination: $ds2) isa process;
	(owned-by: $ds1, owned-by: $ds2, owner: $py) isa ownership;
	(owned-by: $eco1, owner: $cis) isa ownership;
	(employee: $py, employer: $cis) isa employment;
	(environment-has-platform: $aws1, environment-has-platform: $aws2, environment-has-platform: $aws3, environment-has-platform: $aws4, platform-has-environment: $eco1) isa platform-environment;
