insert

organization sub entity
	has name
	plays owner
	plays employer;

platform sub entity
	has name
	has description
	has url
	plays owned-by
	plays platform-has-environment;

environment sub entity
	has name
	plays environment-has-platform
	plays environment-has-tool;

tool sub entity
	has name
	plays tool-has-environment
	plays tool-has-dataset
	plays executor;

dataset sub entity
	has name
	has description
	has type
	has location
	
	#TODO
#	has created
#	has updated
#	has format
#	has url
#	has database
#	has table

	plays owned-by
	plays source
	plays destination
	plays dataset-has-tool
	plays ancestor
	plays descendant;

person sub entity
	has name
	plays employee
	plays owner;

#Relations
employment sub relation
	relates employer
	relates employee;

ownership sub relation
	relates owner
	relates owned-by;

process sub relation
	has name
	relates source
	relates destination
	relates executor;

platform-environment sub relation
	relates platform-has-environment
	relates environment-has-platform;

environment-tool sub relation
	relates environment-has-tool
	relates tool-has-environment;

tool-dataset sub relation
	relates tool-has-dataset
	relates dataset-has-tool;

ancestry sub relation
	relates ancestor
	relates descendant;

#Roles 
employee sub role;
employer sub role;
owner sub role;
owned-by sub role;
source sub role;
destination sub role;
platform-has-environment sub role;
environment-has-platform sub role;
tool-has-environment sub role;
environment-has-tool sub role;
dataset-has-tool sub role;
tool-has-dataset sub role;
ancestor sub role;
descendant sub role;
executor sub role;

#Resources
name sub resource datatype string;
description sub resource datatype string;
location sub resource datatype string;
type sub resource datatype string;
url sub resource datatype string;
#database sub resource datatype string;
#table sub resource datatype string;
#format sub resource datatype string;
#created sub resource datatype string;
#updated sub resource datatype string;


#Rules
$ancestor isa inference-rule 
when {
(source: $s, destination: $d) isa process;
} then {
(ancestor: $s, descendant: $d) isa ancestry; };

$transitive-ancestor isa inference-rule
when {
(ancestor: $a, descendant: $b) isa ancestry;
(ancestor: $b, descendant: $c) isa ancestry; 
} then {
(ancestor: $a, descendant: $c) isa ancestry; };
